repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-json
    - id: requirements-txt-fixer
    - id: pretty-format-json
      args: [--autofix, --indent=4, --no-ensure-ascii]

  - repo: local
    hooks:
    - id: ruff-format
      name: ruff format
      entry: ruff format
      language: system
      types: [python]

    - id: ruff-lint
      name: ruff lint (check + fix)
      entry: ruff check
      language: system
      types: [python]
      args: ["--fix"]
