ARG VERSION=3.12-slim
FROM python:${VERSION}

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

RUN pip install --upgrade pip

ARG USERNAME=devuser
RUN groupadd --gid 1000 $USERNAME && useradd --uid 1000 --gid 1000 -m $USERNAME
RUN apt update \
    && apt-get install -y sudo gcc git micro \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

COPY requirements.txt /home/${USERNAME}/requirements.txt
RUN pip install -r /home/${USERNAME}/requirements.txt

COPY .bashrc /home/${USERNAME}/.bashrc
ENV PATH="/home/${USERNAME}/.local/bin:${PATH}"
USER $USERNAME

WORKDIR /app
