ARG VERSION
FROM python:${VERSION}-slim as builder
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY requirements.txt requirements.txt
RUN uv pip install --system -r requirements.txt

RUN apt update \
    && apt install -y pipx \
    && pipx ensurepath

RUN pipx install rust-just


FROM python:${VERSION}-slim
# copy python installation
COPY --from=builder /usr/local/ /usr/local/

# add developers tools
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
COPY --from=builder /root/.local/bin/just /bin/
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

# create a devuser
ARG USERNAME
ARG USER_GID
ARG USER_UID
ARG WORK_DIR

RUN mkdir -p /$WORK_DIR
RUN useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

USER $USERNAME
RUN ln -s /$WORK_DIR ${HOME}/

# copy bashrc
COPY .bashrc ${HOME}/.bashrc
COPY .bashrc /root/.bashrc

WORKDIR /$WORK_DIR
