ARG VERSION=3.12-slim
FROM python:${VERSION}

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

RUN pip install --upgrade pip
RUN apt update \
    && apt-get install -y sudo gcc git micro

COPY bashrc /root/.bashrc
COPY requirements /root/requirements
RUN pip install -r /root/requirements

WORKDIR /app
