services:
  denver_${name}:
    container_name: denver_${name}
    build:
      context: .
      dockerfile: dockerfile
      args:
        VERSION: ${version}
        USERNAME: ${username}
        USER_UID: ${user_uid}
        USER_GID: ${user_gid}
        WORK_DIR: ${work_dir}
    image: denver/${name}
    volumes:
      - $${PWD}:/${work_dir}:Z
    command: tail -f /dev/null
    stdin_open: true
    env_file: ".env"
    network_mode: "host"
