services:
  denver_{{name}}:
    container_name: denver_{{name}}
    build:
      context: .
      dockerfile: dockerfile
      args:
        VERSION: {{version}}
    volumes:
      - ${PWD}:/app
    command: tail -f /dev/null
    stdin_open: true
    env_file: "env"
    network_mode: "host"
