ARG VERSION
FROM python:${VERSION}

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

ARG USERNAME
{{NO_ROOT}}
USER $USERNAME

# install VSCode + extensions
RUN curl -fsSL https://code-server.dev/install.sh | sh
RUN code-server --install-extension redhat.vscode-yaml \
                --install-extension ms-python.python

ENV PATH="${HOME}/.local/bin:${PATH}"
RUN pip install --upgrade pip

COPY requirements.txt /tmp/requirements.txt
RUN sudo mv /tmp/requirements.txt ${HOME}/requirements.txt

RUN pip install -r ${HOME}/requirements.txt
COPY .bashrc /tmp/.bashrc
RUN sudo mv /tmp/.bashrc ${HOME}/.bashrc

WORKDIR /app
